// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package update_data

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Update is the `update` instruction.
type Update struct {
	Data *uint64

	// [0] = [WRITE] myAccount
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateInstructionBuilder creates a new `Update` instruction builder.
func NewUpdateInstructionBuilder() *Update {
	nd := &Update{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 1),
	}
	return nd
}

// SetData sets the "data" parameter.
func (inst *Update) SetData(data uint64) *Update {
	inst.Data = &data
	return inst
}

// SetMyAccountAccount sets the "myAccount" account.
func (inst *Update) SetMyAccountAccount(myAccount ag_solanago.PublicKey) *Update {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(myAccount).WRITE()
	return inst
}

// GetMyAccountAccount gets the "myAccount" account.
func (inst *Update) GetMyAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

func (inst Update) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Update,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Update) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Update) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Data == nil {
			return errors.New("Data parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.MyAccount is not set")
		}
	}
	return nil
}

func (inst *Update) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Update")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Data", *inst.Data))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=1]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("my", inst.AccountMetaSlice.Get(0)))
					})
				})
		})
}

func (obj Update) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Data` param:
	err = encoder.Encode(obj.Data)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Update) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Data`:
	err = decoder.Decode(&obj.Data)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateInstruction declares a new Update instruction with the provided parameters and accounts.
func NewUpdateInstruction(
	// Parameters:
	data uint64,
	// Accounts:
	myAccount ag_solanago.PublicKey) *Update {
	return NewUpdateInstructionBuilder().
		SetData(data).
		SetMyAccountAccount(myAccount)
}
