// Code generated by Kitex v0.4.2. DO NOT EDIT.

package helloworld

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	hello "toolkit/demon/kitex/hello/kitex_gen/kitex/hello"
)

func serviceInfo() *kitex.ServiceInfo {
	return helloWorldServiceInfo
}

var helloWorldServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "HelloWorld"
	handlerType := (*hello.HelloWorld)(nil)
	methods := map[string]kitex.MethodInfo{
		"SayHello": kitex.NewMethodInfo(sayHelloHandler, newSayHelloArgs, newSayHelloResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "tool.kit",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.4.2",
		Extra:           extra,
	}
	return svcInfo
}

func sayHelloHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(hello.HelloRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(hello.HelloWorld).SayHello(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *SayHelloArgs:
		success, err := handler.(hello.HelloWorld).SayHello(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SayHelloResult)
		realResult.Success = success
	}
	return nil
}
func newSayHelloArgs() interface{} {
	return &SayHelloArgs{}
}

func newSayHelloResult() interface{} {
	return &SayHelloResult{}
}

type SayHelloArgs struct {
	Req *hello.HelloRequest
}

func (p *SayHelloArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(hello.HelloRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SayHelloArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SayHelloArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SayHelloArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in SayHelloArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *SayHelloArgs) Unmarshal(in []byte) error {
	msg := new(hello.HelloRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SayHelloArgs_Req_DEFAULT *hello.HelloRequest

func (p *SayHelloArgs) GetReq() *hello.HelloRequest {
	if !p.IsSetReq() {
		return SayHelloArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SayHelloArgs) IsSetReq() bool {
	return p.Req != nil
}

type SayHelloResult struct {
	Success *hello.HelloResp
}

var SayHelloResult_Success_DEFAULT *hello.HelloResp

func (p *SayHelloResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(hello.HelloResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SayHelloResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SayHelloResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SayHelloResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in SayHelloResult")
	}
	return proto.Marshal(p.Success)
}

func (p *SayHelloResult) Unmarshal(in []byte) error {
	msg := new(hello.HelloResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SayHelloResult) GetSuccess() *hello.HelloResp {
	if !p.IsSetSuccess() {
		return SayHelloResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SayHelloResult) SetSuccess(x interface{}) {
	p.Success = x.(*hello.HelloResp)
}

func (p *SayHelloResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SayHello(ctx context.Context, Req *hello.HelloRequest) (r *hello.HelloResp, err error) {
	var _args SayHelloArgs
	_args.Req = Req
	var _result SayHelloResult
	if err = p.c.Call(ctx, "SayHello", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
