// Code generated by Kitex v0.4.2. DO NOT EDIT.

package helloworld

import (
	server "github.com/cloudwego/kitex/server"
	hello "toolkit/demon/kitex/hello/kitex_gen/kitex/hello"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler hello.HelloWorld, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
