// Code generated by Kitex v0.4.2. DO NOT EDIT.
package helloworld

import (
	server "github.com/cloudwego/kitex/server"
	hello "toolkit/demon/kitex/hello/kitex_gen/kitex/hello"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler hello.HelloWorld, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
